### ISSUE TITLE
orchestration-api-server not scheduled on GKE

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1053]
On a newly created k8s cluster on google cloud using machine type: n1-standard-1 the orchestration-api-server never scheduled but remains Pending state, because of the following error:

```
Events:
  Type     Reason             Age    From                Message
  ----     ------             ----   ----                -------
  Warning  FailedScheduling   4m19s  default-scheduler   0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
  Normal   NotTriggerScaleUp  4m17s  cluster-autoscaler  pod didn't trigger scale-up:
```

The corresponding replica set affinity spec part:

```
spec:
    template:
        spec:
            affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - arm64
```

```
❯ ns version
version v0.0.137 (commit eaa5a75cbccde708f4c65df5851d7d9a1752a0b5)
  commit date 2023-01-15T23:14:16Z
  architecture darwin/arm64
  internal api 62 (cache=1 tools=4)
```
