### ISSUE TITLE
volume configurable fromKubernetesSecret does not generate the proper manifest 

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1141]
Assuming we have the following Kubernetes secret:
```
apiVersion: v1
kind: Secret
metadata:
    name: server-secret
type: Opaque
data:
    bar1: Zm9v
```
Having the following definition in `server.cue`:
```
mounts: {
        "server-secret-bar1": configurable: fromKubernetesSecret: "server-secret:bar1"
    }
```
NS generates the following manifest:
```
 volumes:
  - name: vi--server-secret-bar1
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: server-secret
            path: server-secret-bar1
          name: server-secret
```
That causes the following error:
```
MountVolume.SetUp failed for volume "vi--server-secret-bar1" : references non-existent secret key: server-secret
```
I believe a possible fix would be to have the following manifest instead:
```
volumes:
  - name: vi--server-secret-bar1
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: ba1
            path: bar1
          name: server-secret
```
